/* WARNING: AUTO GENERATED BY GULP: do not edit this file manually. */

export {default as fetch} from './fetch.js';
export {default as vueRouter} from './vueRouter.js';
export {default as vuex} from './vuex.js';
