version: '2'
services:
  assets:
    image: mhart/alpine-node:6.7.0
    volumes:
      - ./../:/app
    working_dir: /app
    command: "./node_modules/.bin/webpack --colors"
    environment:
      NODE_ENV: "${NODE_ENV}"

  # assetserver:
  #   image: nginx:1.11.4-alpine
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./../_dist:/var/www/html
